name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2','8.3']

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          #php-version: '8.3'
          tools: laravel/pint

      - name: scan code repo
        uses: overtrue/phplint@8.1
        with:
          path: .
          options: --exclude=*.log

      - name: Check code style
        run: pint --test

      - name: Install dependencies
        run: composer Install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.service.mysql.port['3306'] }}
          DB_USERNAME: root
          DB_PASSWORD: null
          DB_DATABASE: test



    
